name: Distribute Flutter App to Firebase

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.0"

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "${{ secrets.FIREBASE_APP_ID }}" \
            --groups "${{ env.TESTERS_GROUP }}" \
            --release-notes "$(cat release_notes.txt)"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
